name: Deploy All Stacks

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  # verbosity setting for Terraform logs
  # TF_LOG: INFO

on:
  push:
    branches:
      - main

concurrency:
  group: iac-gcloud-deploy
  cancel-in-progress: false

jobs:
  deploy-org:
    name: Org
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      # Let other stacks finish even if one fails.
      fail-fast: false

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies such as Terramate and Terraform with asdf
        uses: asdf-vm/actions/install@v3

      - name: List changed stacks
        id: list
        run: |
          terramate -C stacks list --changed > >(tee /tmp/stdout.txt) 2> >(tee /tmp/stderr.txt)
          EXIT_CODE=$?
          echo "stdout<<STDOUT" >>$GITHUB_OUTPUT
          cat /tmp/stdout.txt >>$GITHUB_OUTPUT
          echo "STDOUT" >>$GITHUB_OUTPUT
          exit ${EXIT_CODE}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github
      - run: aws sts get-caller-identity

      - name: Run Terraform init on changed stacks
        if: steps.list.outputs.stdout
        id: init
        run: |
          terramate -C stacks run --changed --disable-check-gen-code -- terraform init -lock-timeout=5m

      - name: Create Terraform plan on changed stacks
        if: steps.list.outputs.stdout
        id: plan
        run: |
          terramate -C stacks run --changed --disable-check-gen-code -- terraform plan -lock-timeout=5m -out out.tfplan

      - name: Apply planned changes on changed stacks
        if: steps.list.outputs.stdout
        id: apply
        run: |
          terramate -C stacks run --changed --disable-check-gen-code --cloud-sync-deployment -- terraform apply -input=false -auto-approve -lock-timeout=5m out.tfplan

      - name: Run drift detection
        if: steps.list.outputs.stdout
        id: drift
        run: |
          terramate -C stacks run --changed --disable-check-gen-code --cloud-sync-drift-status --cloud-sync-terraform-plan-file=drift.tfplan -- terraform plan -out drift.tfplan -detailed-exitcode
